/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventofcode;

/*
Keeping this here in case I need to run a CLI at some point soon.
I haven't done java in a while so I'd rather have this around.
If I end up not using it, I'll delete 🙂👍
*/
public class App {

  public static void main(String[] args) {
    System.out.println("Hello World!");
  }
}
